name: Validate Tag

on:
#  schedule:
#    - cron: 5 6 * * 0
  workflow_dispatch:
  watch:
    types: started

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set latest release
      run: |
        latest_release="$(curl -s https://github.com/openwrt/openwrt/tags | grep -Eo "v[0-9\.]+\-*r*c*[0-9]*.tar.gz" | sed -n '/[2-9][3-9]/p' | sed -n 1p | sed 's/.tar.gz//g')"
        echo "latest_release=${latest_release}" >> $GITHUB_ENV

    - name: Create tag if not exists
      run: |
        git tag -a ${{ env.latest_release }} -m "Release ${{ env.latest_release }}"
        git push origin ${{ env.latest_release }}

    - name: Create release
      id: create_release
      uses: ncipollo/release-action@main
      with:
        name: OpenWRT-${{ env.latest_release }}
        allowUpdates: true
        prerelease: false
        tag: ${{ env.latest_release }}
        commit: 23.05  # 替换为你的实际提交哈希或分支名称
        replacesArtifacts: true
        token: ${{ secrets.TOKEN }}
        artifacts: ./artifact/*.zip
