name: Validate Tag

on:
#  schedule:
#    - cron: 5 6 * * 0
  workflow_dispatch:
  watch:
    types: started

jobs:
  validate-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set latest release
      run: echo "latest_release=v1.0.0" >> $GITHUB_ENV  # 替换为你的实际标签名称
      
    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Validate tag
      id: validate_tag
      run: |
        TAG_NAME=${{ env.latest_release }}
        RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/git/refs/tags/$TAG_NAME")
        
        if [ "$(echo $RESPONSE | jq -r '.message')" == "Not Found" ]; then
          echo "Tag $TAG_NAME does not exist."
          exit 1
        else
          echo "Tag $TAG_NAME is valid."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Create release
      if: success()
      id: create_release
      uses: ncipollo/release-action@main
      with:
        name: OpenWRT-${{ env.latest_release }}
        allowUpdates: true
        prerelease: false
        tag: ${{ env.latest_release }}
        commit: 23.05  # 替换为你的实际提交哈希或分支名称
        replacesArtifacts: true
        token: ${{ secrets.TOKEN }}
        artifacts: ./artifact/*.zip
