name: Execute Actions on Repository Update

on:
  workflow_dispatch: # 由其他工作流触发

jobs:
  execute-on-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 在这里添加你希望执行的任务
      - name: Run a script
        run: |
          echo "Repository was updated. Performing tasks..."
          # 这里可以添加你希望执行的任何脚本或任务
